export const fieldToDescription = {
  "status": "Status",
  "type": "Type",
  "containerId": "containerId",
  "itemId": "itemId",
  "description": "description",
  "pickInstruction": "pickInstruction",
  "planQuantity": "planQuantity",
  "planMinQuantity": "planMinQuantity",
  "planMaxQuantity": "planMaxQuantity",
  "actualQuantity": "actualQuantity",
  "locationId": "locationId",
  "pickerId": "pickerId",
  "posAlongPath": "posAlongPath",
  "created": "created",
  "assigned": "assigned",
  "started": "started",
  "completed": "completed",
  "needsScan": "needsScan",
  "gtin": "gtin",
  "purpose": "purpose",
  "pathName": "pathName",
  "substituteAllowed": "substituteAllowed",
  "substitution": "substitution",
  "alreadyShorted": "alreadyShorted",
}
