import Promise from "bluebird";

const cartInfo = { "className": "Che", "domainId": "CHE_13", "persistentId": "165dc7ed-c85a-49be-b20b-46d1c9c358cc", "deviceGuid": "0x000001df", "description": "", "lastBatteryLevel": 0, "networkDeviceStatus": null, "lastContactTime": null, "networkAddress": 0, "color": "GREEN", "scannerType": "CODECORPS3600", "processMode": "SETUP_ORDERS", "lastScannedLocation": null, "associateToCheGuid": null, "cheLighting": "POSCON_V1" };
const plannedWork = {
    "sortedBy": null,
    "results": [
        {
            "domainId": "145644632652700",
            "persistentId": "da7da94b-12b4-4892-a000-2e9f6ba9c502",
            "type": "PLAN",
            "status": "NEW",
            "containerId": "44935940",
            "itemId": "673419230391",
            "description": "",
            "pickInstruction": "P1001171",
            "planQuantity": 1,
            "planMinQuantity": 1,
            "planMaxQuantity": 1,
            "actualQuantity": 0,
            "locationId": "F1.FACILITY_UNSPECIFIED",
            "pickerId": null,
            "ledCmdStream": "[]",
            "posConCmdStream": null,
            "groupAndSortCode": "0001",
            "posAlongPath": 0,
            "created": 1456446326527,
            "assigned": 1456446326380,
            "started": null,
            "completed": null,
            "needsScan": true,
            "gtin": "",
            "purpose": "WiPurposeOutboundPick",
            "pathName": null,
            "substituteAllowed": false,
            "substitution": null,
            "alreadyShorted": false
        },
        {
            "domainId": "145644632651700",
            "persistentId": "60678022-18bf-432c-bd89-4bbbba04247f",
            "type": "PLAN",
            "status": "NEW",
            "containerId": "44935940",
            "itemId": "673419230407",
            "description": "",
            "pickInstruction": "P2001771",
            "planQuantity": 1,
            "planMinQuantity": 1,
            "planMaxQuantity": 1,
            "actualQuantity": 0,
            "locationId": "F1.FACILITY_UNSPECIFIED",
            "pickerId": null,
            "ledCmdStream": "[]",
            "posConCmdStream": null,
            "groupAndSortCode": "0002",
            "posAlongPath": 0,
            "created": 1456446326517,
            "assigned": 1456446326380,
            "started": null,
            "completed": null,
            "needsScan": true,
            "gtin": "",
            "purpose": "WiPurposeOutboundPick",
            "pathName": null,
            "substituteAllowed": false,
            "substitution": null,
            "alreadyShorted": false
        },
        {
            "domainId": "145644632644800",
            "persistentId": "d8a7f5e4-af98-4e5c-89a5-d032f2bdfb42",
            "type": "PLAN",
            "status": "NEW",
            "containerId": "44935940",
            "itemId": "673419250771",
            "description": "",
            "pickInstruction": "L100401E",
            "planQuantity": 1,
            "planMinQuantity": 1,
            "planMaxQuantity": 1,
            "actualQuantity": 0,
            "locationId": "F1.FACILITY_UNSPECIFIED",
            "pickerId": null,
            "ledCmdStream": "[]",
            "posConCmdStream": null,
            "groupAndSortCode": "0003",
            "posAlongPath": 0,
            "created": 1456446326443,
            "assigned": 1456446326380,
            "started": null,
            "completed": null,
            "needsScan": true,
            "gtin": "",
            "purpose": "WiPurposeOutboundPick",
            "pathName": null,
            "substituteAllowed": false,
            "substitution": null,
            "alreadyShorted": false
        },
        {
            "domainId": "145644632653900",
            "persistentId": "fdf3f870-93df-42aa-a3aa-3bbc00e24675",
            "type": "PLAN",
            "status": "NEW",
            "containerId": "44935940",
            "itemId": "673419210522",
            "description": "",
            "pickInstruction": "L200301B",
            "planQuantity": 1,
            "planMinQuantity": 1,
            "planMaxQuantity": 1,
            "actualQuantity": 0,
            "locationId": "F1.FACILITY_UNSPECIFIED",
            "pickerId": null,
            "ledCmdStream": "[]",
            "posConCmdStream": null,
            "groupAndSortCode": "0004",
            "posAlongPath": 0,
            "created": 1456446326539,
            "assigned": 1456446326380,
            "started": null,
            "completed": null,
            "needsScan": true,
            "gtin": "",
            "purpose": "WiPurposeOutboundPick",
            "pathName": null,
            "substituteAllowed": false,
            "substitution": null,
            "alreadyShorted": false
        },
        {
            "domainId": "145644632655200",
            "persistentId": "3eed394d-ee90-48eb-82c4-1d3d118af01c",
            "type": "PLAN",
            "status": "NEW",
            "containerId": "44935940",
            "itemId": "673419190510",
            "description": "",
            "pickInstruction": "P4002161",
            "planQuantity": 1,
            "planMinQuantity": 1,
            "planMaxQuantity": 1,
            "actualQuantity": 0,
            "locationId": "F1.FACILITY_UNSPECIFIED",
            "pickerId": null,
            "ledCmdStream": "[]",
            "posConCmdStream": null,
            "groupAndSortCode": "0005",
            "posAlongPath": 0,
            "created": 1456446326552,
            "assigned": 1456446326380,
            "started": null,
            "completed": null,
            "needsScan": true,
            "gtin": "",
            "purpose": "WiPurposeOutboundPick",
            "pathName": null,
            "substituteAllowed": false,
            "substitution": null,
            "alreadyShorted": false
        },
        {
            "domainId": "145644632650800",
            "persistentId": "ea0beaa9-2fa6-4f6b-9de7-6449dc12b6d3",
            "type": "PLAN",
            "status": "NEW",
            "containerId": "44935940",
            "itemId": "673419251723",
            "description": "",
            "pickInstruction": "P6001011",
            "planQuantity": 1,
            "planMinQuantity": 1,
            "planMaxQuantity": 1,
            "actualQuantity": 0,
            "locationId": "F1.FACILITY_UNSPECIFIED",
            "pickerId": null,
            "ledCmdStream": "[]",
            "posConCmdStream": null,
            "groupAndSortCode": "0006",
            "posAlongPath": 0,
            "created": 1456446326508,
            "assigned": 1456446326380,
            "started": null,
            "completed": null,
            "needsScan": true,
            "gtin": "",
            "purpose": "WiPurposeOutboundPick",
            "pathName": null,
            "substituteAllowed": false,
            "substitution": null,
            "alreadyShorted": false
        }
    ],
    "next": null,
    "total": 6
}

export function getPlannedWork() {
  return Promise.delay(Promise.resolve(plannedWork), 500);
}

export function getCart(domainId) {
  return Promise.delay(Promise.resolve(cartInfo), 500);
}