// This file was autogenerated by /Users/jeffw/Source/eclipse/workspace-escontroller/CodeShelfRIA/lib/GoogleClosureLibrary/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../../src/js_uncompiled/base.js', ['goog'], []);
goog.addDependency('../../../../src/js_uncompiled/foo/bar.js', ['closureexample.foo.Bar'], ['goog.dom']);
goog.addDependency('../../../../src/js_uncompiled/init.js', ['closureexample.init'], ['closureexample.foo.Bar', 'goog.dom']);
