// This file was autogenerated by /Users/jeffw/Source/eclipse/workspace-escontroller/CodeShelfUX/lib/GoogleClosureLibrary/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../../src/js_uncompiled/ListView.js', ['codeshelf.listview'], ['jquery.min', 'slickgrid.columnpicker', 'slickgrid.core', 'slickgrid.dataview', 'slickgrid.editors', 'slickgrid.firebugx', 'slickgrid.grid', 'slickgrid.pager', 'slickgrid.rowselection']);
goog.addDependency('../../../../src/js_uncompiled/MainPage.js', ['codeshelf.mainpage'], ['goog.dom', 'goog.dom.ViewportSizeMonitor', 'goog.dom.query', 'goog.events', 'goog.events.EventType', 'goog.fx.Dragger', 'goog.math.Size', 'goog.style', 'goog.window', 'jquery.rotate']);
goog.addDependency('../../../JQuery/jquery-1.7.min.js', ['jquery.min'], []);
goog.addDependency('../../../JQuery/jquery-ui-1.8.16.custom.min.js', ['jquery.ui'], []);
goog.addDependency('../../../JQuery/jquery.event.drag-2.0.min.js', ['jquery.event.drag'], []);
goog.addDependency('../../../JQuery/jquery.event.drop-2.0.min.js', ['jquery.event.drop'], []);
goog.addDependency('../../../JQuery/jquery.jsonp-1.1.0.min.js', ['jquery.jsonp'], []);
goog.addDependency('../../../JQuery/jquery.rotate.2.1.js', ['jquery.rotate'], ['jquery.min']);
goog.addDependency('../../../JQuery/jquery.sparkline.min.js', ['jquery.sparkline'], []);
goog.addDependency('../../../SlickGrid/controls/slick.columnpicker.js', ['slickgrid.columnpicker'], ['jquery.min']);
goog.addDependency('../../../SlickGrid/controls/slick.pager.js', ['slickgrid.pager'], []);
goog.addDependency('../../../SlickGrid/lib/firebugx.js', ['slickgrid.firebugx'], []);
goog.addDependency('../../../SlickGrid/lib/jquery.simulate.js', ['jquery.event.simulate'], []);
goog.addDependency('../../../SlickGrid/plugins/slick.rowselectionmodel.js', ['slickgrid.rowselection'], []);
goog.addDependency('../../../SlickGrid/slick.core.js', ['slickgrid.core'], ['jquery.event.drag', 'jquery.event.drop', 'jquery.min', 'jquery.ui']);
goog.addDependency('../../../SlickGrid/slick.dataview.js', ['slickgrid.dataview'], []);
goog.addDependency('../../../SlickGrid/slick.editors.js', ['slickgrid.editors'], []);
goog.addDependency('../../../SlickGrid/slick.grid.js', ['slickgrid.grid'], ['jquery.event.drag']);
