export const cartFieldsSetting = {
  order: ["domainId", "className", "deviceGuid", "description", "lastBaterryLevel", "lastContactTime", "networkDeviceStatus", "scannerType", "processMode", "color", "cheLighting", "lastScannedLocation", "networkAddress"],
  visibility: {
    "domainId":true,
    "className":true,
    "deviceGuid":true,
    "description": true,
    "cheLighting": true,
    "lastBaterryLevel": true,
    "lastContactTime": true,
    "color": true,
    "lastScannedLocation": true,
    "networkAddress": true,
    "networkDeviceStatus": true,
    "processMode": true,
    "scannerType": true,
  },
};

export const historyFieldsSetting = {
  order: ["type", "itemId", "itemUom", "itemDescription", "itemLocation", "wiPlanQuantity",
  "wiActualQuantity", "workerName", "orderId", "deviceName", "deviceGuid", "createdAt", "workerId",
  "orderDetailId", "workInstructionId", "resolved", "resolvedAt", "resolvedBy"],
  visibility: {
    "type": true,
    "itemId": true,
    "itemUom": true,
    "itemDescription": true,
    "itemLocation": true,
    "wiPlanQuantity": true,
    "wiActualQuantity": true,
    "orderId": true,
    "orderDetailId": true,
    "workerName": true,
    "workInstructionId": true,
    "resolved": true,
    "resolvedAt": true,
    "resolvedBy": true,
    "deviceName": true,
    "deviceGuid": true,
    "workerId": true,
    "createdAt": true,
  },
};
