export const fieldToDescription = {
    "persistentId":"persistentId",
    "active":"active",
    "firstName": "firstName",
    "lastName": "lastName",
    "middleInitial": "middleInitial",
    "domainId": "Badge ID",
    "groupName": "groupName",
    "hrId": "hrId",
    "updated": "updated",
    "lastLogin": "lastLogin",
    "lastLogout": "lastLogout",
    "lastChePersistentId": "lastChePersistentId",
    "badgeUnique": "badgeUnique",
    "className": "className",
    "firstName+middleInitial+lastName": "Name",
};
